feat: activeUntil and new withdrawable impl
radicle-dev/radicle-drips pull request #15
Opened 2021-10-08 15:53 UTC by xmxanuel

- new function `activeUntil`
- new behaviour of `withdrawable`
- active(tokenId) based on `activeUntil`
- updated deploy script
- removed temporary nftTypes array  from constructor

2021-10-08 15:53 UTC, manuelpolzhofer commented on src/nft.sol
> +    mapping (uint => uint64) public minted;
I moved it here but we could also store it in the pool contract

2021-10-11 08:25 UTC, CodeSandwich requested changes
I love how expiration option C just wiped some of the most complex logic 😌

2021-10-11 08:25 UTC, CodeSandwich commented on src/nft.sol
> +            return type(uint128).max;
That's generous :sweat_smile: 
```suggestion
            return pool.withdrawableSubSender(address(this), tokenId);
```

2021-10-11 08:43 UTC, CodeSandwich commented on src/nft.sol
> +            return type(uint128).max;
BTW my suggestion isn't correct either, it doesn't take into account locking funds.

2021-10-11 08:55 UTC, manuelpolzhofer commented on src/nft.sol
> +            return type(uint128).max;
Because you only need to lock your `amtPerSec * cycleSecs` which is always zero in that case.

2021-10-11 10:18 UTC, merged