feat: integrate metadata and svg
radicle-dev/radicle-drips pull request #25
Opened 2021-10-20 12:39 UTC by xmxanuel

please review #19 first

2021-10-20 12:41 UTC, manuelpolzhofer commented on src/registry.sol
> +    function changeBuilder(address newBuilder) public onlyGovernance {
The other open question.
Should the Radicle Funding be able to change the SVG builder for all projects?
(for new designs etc)

2021-11-03 11:36 UTC, manuelpolzhofer commented on src/builder.sol
> +    string public defaultBackground =
This is temporary

2021-11-03 14:21 UTC, CodeSandwich requested changes

2021-11-03 14:21 UTC, CodeSandwich commented on src/builder.sol
> +    ) public view returns (string memory) {
IIUC `Builder` can be used directly as `IBuilder` and then it gets the default background, or as a backend for a custom implementation of `IBuilder` which may then provide a custom background. Wouldn't it make sense to separate these use cases into two separate contracts? One implementing `IBuilder` using the default background and the other exposing `buildMetaData` accepting a custom background. I wonder how would that impact gas usage? Deployment would be the same and SVG generation is done in calls anyway, so it should be fine?

2021-11-03 14:21 UTC, CodeSandwich commented on src/builder.sol
> +                    active: tokenActiveString,
A bit lighter approach:
```suggestion
                    active: active ? "true" : "false",
```

2021-11-03 14:21 UTC, CodeSandwich commented on src/builder.sol
> +    string public defaultBackground =
```suggestion
    string const defaultBackground =
```

2021-11-03 14:21 UTC, CodeSandwich commented on src/nft.sol
> +    event NewBuilder(address indexed Builder);
Why `indexed`?

2021-11-03 14:21 UTC, CodeSandwich commented on src/nft.sol
> +    function init(string calldata name_, string calldata symbol_, address owner, string calldata ipfsHash, InputNFTType[] memory inputNFTTypes, address builder_) public {
```suggestion
    function init(string calldata name_, string calldata symbol_, address owner, string calldata ipfsHash, InputNFTType[] memory inputNFTTypes, IBuilder builder_) public {
```

2021-11-03 14:21 UTC, CodeSandwich commented on src/nft.sol
> +        builder = IBuilder(builder_);
Do we need to `emit NewBuilder(builder_);`? `changeBuilder(builder_)` would probably do that for us elegantly.

2021-11-03 14:21 UTC, CodeSandwich commented on src/nft.sol
> +    function changeBuilder(address newBuilder) public onlyOwner {
```suggestion
    function changeBuilder(IBuilder newBuilder) public onlyOwner {
```

2021-11-03 14:21 UTC, CodeSandwich commented on src/registry.sol
> +        builder = builder_;
Do we need to `emit NewBuilder(builder_);`? `changeBuilder(builder_)` would probably do that for us elegantly.

2021-11-03 14:21 UTC, CodeSandwich commented on src/registry.sol
> +    event NewBuilder(address indexed builder);
Does `builder` need to be `indexed`? Do `NewProject` parameters need to be `indexed`?

2021-11-03 14:45 UTC, manuelpolzhofer commented on src/builder.sol
> +        "    -10px)} 100%{transform: translate(0, 0)} } .triangle-float3 { animation: float3 6s infinite; }"
We still need to decide, what we want to use. 

I used this library to generate the animation: https://bgjar.com/animated-shape
Maybe we can abstract it in the contract and it can be passed in the constructor.

2021-11-03 14:46 UTC, manuelpolzhofer commented on src/builder.sol
> +    function toTwoDecimals(uint128 number)
If it is just a view function, why not. I see it more as a helpful library in that case.

2021-11-03 14:46 UTC, manuelpolzhofer commented on src/builder.sol
> +                    active: tokenActiveString,
👍

2021-11-03 14:50 UTC, manuelpolzhofer commented on src/nft.sol
> +    function init(string calldata name_, string calldata symbol_, address owner, string calldata ipfsHash, InputNFTType[] memory inputNFTTypes, address builder_) public {
After trying out the interface approach for address parameter, I came to the conclusion that it is horrible. 

Solidity can't detect the interface. You always need to import the actual contract and the interface. Cast to address then to the interface. 

I think it more elegant to just pass the addresses for contract dependencies. I want to change the other dependencies as well to type address again. If you agree :)

2021-11-03 14:52 UTC, manuelpolzhofer commented on src/builder.sol
> +contract Builder {
I programmed too much Golang :)

2021-11-03 14:59 UTC, CodeSandwich commented on src/builder.sol
> +contract Builder {
This is probably why you had problems with https://github.com/radicle-dev/funding-contracts/pull/25#discussion_r742020079

2021-11-04 07:37 UTC, CodeSandwich commented on src/builder.sol
> +    function toTwoDecimals(uint128 number)
It needlessly expands the API surface, we're risking that somebody might start using it instead of rolling their own and get us stuck with that particular signature.

2021-11-10 07:16 UTC, manuelpolzhofer commented on src/builder.sol
> +contract Builder {
fixed

2021-11-10 07:16 UTC, manuelpolzhofer commented on src/builder.sol
> +    ) public view returns (string memory) {
custom background image functionality removed

2021-11-10 07:17 UTC, manuelpolzhofer commented on src/builder.sol
> +                    active: tokenActiveString,
fixed

2021-11-10 07:17 UTC, manuelpolzhofer commented on src/nft.sol
> +    function init(string calldata name_, string calldata symbol_, address owner, string calldata ipfsHash, InputNFTType[] memory inputNFTTypes, address builder_) public {
fixed

2021-11-10 07:17 UTC, manuelpolzhofer commented on src/registry.sol
> +        builder = builder_;
fixed

2021-11-10 07:17 UTC, manuelpolzhofer commented on src/registry.sol
> +    event NewBuilder(address indexed builder);
fixed

2021-11-10 07:26 UTC, manuelpolzhofer commented on src/nft.sol
> +        nftTypes[newTypeId].ipfsHash = ipfsHash;
I will make this more efficiently in the upcoming PRs see #34

2021-11-10 11:31 UTC, CodeSandwich reviewed
Looks good, I only really have nitpicks

2021-11-10 11:31 UTC, CodeSandwich commented on src/builder.sol
> +    struct Data {
Should this struct exist? It seems like most of its fields are usually not set and ignored. IMO it could improve readability if these parameters were passed around explicitly and only to functions actually needing them.

2021-11-10 11:31 UTC, CodeSandwich commented on src/builder.sol
> +                                "}"
How about passing around `imageObj` without the JSON key part?
```suggestion
                                ', "image": "',
                                imageObj,
                                "'}"
```

2021-11-10 11:31 UTC, CodeSandwich commented on src/builder.sol
> +                                data.active,
How about passing around `active` as a boolean?
```suggestion
                                data.active ? "true" : "false",
```

2021-11-10 11:31 UTC, CodeSandwich commented on src/nft.sol
> +    bool        public initialized;
Why `public`?

2021-11-10 11:31 UTC, CodeSandwich commented on src/nft.sol
> +        return "";
According to ERC-721 we should throw in that case

2021-11-10 14:55 UTC, manuelpolzhofer commented on src/nft.sol
> +    bool        public initialized;
If you deploy it and you want to check if `init` has been already called. Currently with registry not needed but I think the state of initialisation should be public

2021-11-10 14:56 UTC, manuelpolzhofer commented on src/builder.sol
> +                                "}"
Agree, thats more elegant and smaller length.

2021-11-10 14:57 UTC, manuelpolzhofer commented on src/builder.sol
> +    struct Data {
Building a SVG in Solidity is a fight against stack too deep. Thats the reason.

2021-11-10 14:57 UTC, manuelpolzhofer commented on .solhintignore
> +src/Builder.sol
I will add it.

2021-11-10 14:57 UTC, manuelpolzhofer commented on yarn.lock
Let me check. Otherwise we would have a different yarn lock each time :)

2021-11-10 16:30 UTC, CodeSandwich commented on yarn.lock
Fixed: https://github.com/radicle-dev/funding-contracts/pull/40

2021-11-10 17:26 UTC, CodeSandwich commented on src/builder.sol
> +    struct Data {
I've done it: https://github.com/radicle-dev/funding-contracts/pull/41. I haven't been struck with the stack too deep issue even once, there are always just a few local variables in scope.

2021-11-11 14:02 UTC, manuelpolzhofer commented on .solhintignore
> +src/Builder.sol
fixed

2021-11-11 14:03 UTC, manuelpolzhofer commented on src/nft.sol
> +        return "";
fixed

2021-11-11 14:08 UTC, manuelpolzhofer commented on src/builder.sol
> +            );
fixed

2021-11-11 14:19 UTC, CodeSandwich approved these changes
Good work! :rocket:

2021-11-11 14:51 UTC, merged