feat: one time give support
radicle-dev/radicle-drips pull request #44
Opened 2021-11-18 10:35 UTC by manuelpolzhofer

The PR is still in draft mode but I think it is good to discuss the idea.

I think we should have a clear separation between on-time give and streaming supporters.

**One Time Give**
- the NFT type has a minGiveAmt
- no interaction with the pool contract
- not possible to lock funds
- will not get inactive
- influence => giveAmt 

We need an additional flag to indicate if it is a streaming supporter.

Just storing `minAmtPer = 0` is not possible because we still want to have a `minGiveAmt`. 

First, I wanted to keep just one `mint` method but `amt` would have different purposes depending on the streaming flag. The user should not confuse this two.

I will work on the overall naming in a separate PR

2021-11-19 14:44 UTC, CodeSandwich commented on src/nft.sol
> +    bool streaming;
Would it be useful to generalize into something like this?
```suggestion
    uint128 minAmtPerSec;
    uint128 minGive;
```
I wonder if we could ever need streaming tokens with a required upfront donation :thinking: That generalization would certainly slim down the API.

2021-11-19 16:56 UTC, manuelpolzhofer commented on src/nft.sol
> +    bool streaming;
I think too many options will get too complicated but it would be nice to generalize it if possible.

2021-11-22 08:54 UTC, CodeSandwich requested changes

2021-11-22 08:54 UTC, CodeSandwich commented on src/nft.sol
> +        require(giveAmt > nftTypes[typeId].minAmt, "giveAmt-too-low");
Shouldn't we:
```suggestion
        require(giveAmt > nftTypes[typeId].minAmt, "giveAmt-too-low");
        require(nftTypes[typeId].streaming, "nft-type-not-streaming");
```
Otherwise you can configure a streaming NFT and I can mint it as a 1-time, pay 1 second and keep it forever :smile:

2021-11-22 08:54 UTC, CodeSandwich commented on src/nft.sol
> +            return nfts[tokenId].amt;
I know that it's just the first version and we need to decide what to actually do here, but this algorithm is so insanely unbalanced, that it's going to be difficult even to try out using both token types in parallel. This algorithm may not be very good, but at least it puts influence per Dai spent in the same ballpark:
```suggestion
            uint64 multiplier = nfts[tokenId].streaming ? pool.cycleSecs() : 1;
            return nfts[tokenId].amt * multiplier;
```

2021-11-22 08:54 UTC, CodeSandwich commented on src/nft.sol
> +        require(nftTypes[tokenType(tokenId)].streaming && _exists(tokenId), "not-a-streaming-nft");
`onlyTokenHolder` takes care of `_exists`, because it calls `ownerOf`, which requires that the token exists.
```suggestion
        require(nftTypes[tokenType(tokenId)].streaming, "not-a-streaming-nft");
```

2021-11-22 10:15 UTC, manuelpolzhofer commented on src/nft.sol
> +            return nfts[tokenId].amt;
Yeah, currently you can't really compare them.  Your suggestion might be a good first step. In the idea case we would store the minting `block.timestamp` and use the total amount given for both. 

If it is later possible to topUp inactive once again, it will get tricky again.

2021-11-23 10:52 UTC, merged